In [5]:
import cv2, pafy

url   = "https://www.youtube.com/watch?v=HpdO5Kq3o7Y"
video = pafy.new(url)
best  = video.getbest(preftype="any")
#documentation: https://pypi.org/project/pafy/

capture = cv2.VideoCapture(best.url)
check, frame = capture.read()
print (check, frame)

cv2.imshow('frame',frame)
cv2.waitKey(10)

capture.release()
cv2.destroyAllWindows()

True [[[206 206 206]
  [206 206 206]
  [206 206 206]
  ...
  [152 146 134]
  [153 147 135]
  [155 149 137]]

 [[204 204 204]
  [204 204 204]
  [204 204 204]
  ...
  [153 147 135]
  [153 147 135]
  [154 148 136]]

 [[201 201 201]
  [201 201 201]
  [201 201 201]
  ...
  [154 148 136]
  [154 148 136]
  [153 147 135]]

 ...

 [[147 150 155]
  [147 150 155]
  [153 156 161]
  ...
  [134 135 140]
  [137 138 143]
  [137 138 143]]

 [[141 144 149]
  [144 147 152]
  [153 156 161]
  ...
  [136 137 142]
  [136 137 142]
  [137 138 143]]

 [[139 142 147]
  [141 144 149]
  [152 155 160]
  ...
  [140 141 146]
  [139 140 145]
  [137 138 143]]]


In [2]:
import cv2, pafy
URL = "https://www.youtube.com/watch?v=dQw4w9WgXcQ" #URL to parse
play = pafy.new(URL).streams[-1] #'-1' means read the lowest quality of video.
assert play is not None # we want to make sure their is a input to read.
stream = cv2.VideoCapture(play.url) #create a opencv video stream.

In [3]:
from torch import hub # Hub contains other models like FasterRCNN
model = torch.hub.load( \
                      'ultralytics/yolov5', \
                      'yolov5s', \
                      pretrained=True)

NameError: name 'torch' is not defined